`timescale 1ns / 1ps

module tb_pea_top;

    // =========================================================================
    // Parameters & Signals
    // =========================================================================
    localparam DATA_WIDTH = 8;
    localparam ADDR_WIDTH = 16;
    
    logic clk;
    logic rst_n;
    logic start;
    logic done;
    
    // Configuration Bus
    logic [7:0]  cfg_addr;
    logic [31:0] cfg_data;
    logic        cfg_we;
    
    // Memory Interface
    logic [ADDR_WIDTH-1:0] wb_read_addr;
    logic                  wb_re;
    logic [15:0][7:0]      wb_read_data;
    
    logic [ADDR_WIDTH-1:0] ifm_read_addr;
    logic                  ifm_re;
    logic [15:0][7:0]      ifm_read_data;
    
    logic [ADDR_WIDTH-1:0] ofm_write_addr;
    logic                  ofm_we;
    logic [15:0][7:0]      ofm_write_data;

    // =========================================================================
    // Mock SRAM Arrays
    // =========================================================================
    // 128-bit wide memories
    logic [127:0] ifm_mem        [0:1023];
    logic [127:0] weight_mem     [0:15];
    logic [31:0]  bias_mem       [0:15];
    logic [127:0] golden_ofm_mem [0:1023];

    // =========================================================================
    // Device Under Test (DUT)
    // =========================================================================
    pea_top #(
        .DATA_WIDTH(DATA_WIDTH),
        .PSUM_WIDTH(32),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .start(start),
        .done(done),
        .cfg_addr(cfg_addr),
        .cfg_data(cfg_data),
        .cfg_we(cfg_we),
        .wb_read_addr(wb_read_addr),
        .wb_re(wb_re),
        .wb_read_data(wb_read_data),
        .ifm_read_addr(ifm_read_addr),
        .ifm_re(ifm_re),
        .ifm_read_data(ifm_read_data),
        .ofm_write_addr(ofm_write_addr),
        .ofm_we(ofm_we),
        .ofm_write_data(ofm_write_data)
    );

    // =========================================================================
    // Memory Read Logic
    // =========================================================================
    // Mux for Weight (0-15) and Bias (16-31)
    always_comb begin
        if (wb_re) begin
            if (wb_read_addr < 16)
                wb_read_data = weight_mem[wb_read_addr];
            else
                // Bias is 32-bit, zero-extended to 128-bit
                wb_read_data = {96'd0, bias_mem[wb_read_addr - 16]};
        end else begin
            wb_read_data = '0;
        end
    end

    // IFM Read
    assign ifm_read_data = ifm_re ? ifm_mem[ifm_read_addr] : '0;

    // =========================================================================
    // Clock Generation
    // =========================================================================
    initial begin
        clk = 0;
        forever #5 clk = ~clk; // 100MHz
    end

    // =========================================================================
    // Main Test Sequence
    // =========================================================================
    initial begin
        // Initialize signals
        rst_n = 0;
        start = 0;
        cfg_we = 0;
        cfg_addr = 0;
        cfg_data = 0;
        
        // Load Hex Files (Generated by Python)
        // Adjust the paths to wherever your hex files are located!
        $readmemh("../tb/hex/ifm.hex", ifm_mem);
        $readmemh("../tb/hex/weight.hex", weight_mem);
        $readmemh("../tb/hex/bias.hex", bias_mem);
        $readmemh("../tb/hex/expected_ofm.hex", golden_ofm_mem);
        
        $display("---------------------------------------------------------");
        $display("[TB] Mock SRAMs initialized with Hex Data.");
        
        // Reset sequence
        #20 rst_n = 1;
        #10;
        
        // Write Configurations (Matching the Python Testbench)
        // e.g., N_PIXELS = 25 (which maps to 5x5 spatial, C_in=1, etc. in AGU)
        // Since we are running a flattened tile in Python:
        // C_in loops 25 times, kx=1, ky=1, out_x=1, out_y=1
        write_cfg(8'h00, 1);  // reg_ifm_width
        write_cfg(8'h04, 1);  // reg_ifm_height
        write_cfg(8'h08, 26); // reg_channels_in (loop_cin runs up to reg_channels_in - 1) => 25 iterations
        write_cfg(8'h0C, 16); // reg_channels_out
        write_cfg(8'h10, 1);  // reg_kernel_size
        write_cfg(8'h14, 2);  // reg_right_shift = 2
        write_cfg(8'h18, 0);  // reg_row_stride (Not used since Y=0)
        write_cfg(8'h1C, 0);  // reg_col_stride (Not used since X=0)
        
        $display("[TB] Configuration Written.");
        
        // Start Compute
        @(posedge clk);
        start = 1;
        @(posedge clk);
        start = 0;
        
        $display("[TB] Sent START signal. Waiting for DONE...");
        
        // Wait for done
        wait(done == 1);
        @(posedge clk);
        
        $display("[TB] PEA Top Finished Processing!");
        $display("---------------------------------------------------------");
        $finish;
    end
    
    // Task to write Configuration
    task write_cfg(input [7:0] addr, input [31:0] data);
        begin
            @(posedge clk);
            cfg_we <= 1;
            cfg_addr <= addr;
            cfg_data <= data;
            @(posedge clk);
            cfg_we <= 0;
        end
    endtask

    // =========================================================================
    // Scoreboard: Check OFM against Golden Data
    // =========================================================================
    integer error_count = 0;
    
    always_ff @(posedge clk) begin
        if (ofm_we) begin
            if (ofm_write_data !== golden_ofm_mem[ofm_write_addr]) begin
                $display("[ERROR] Mismatch at addr %0d!", ofm_write_addr);
                $display("        Hardware : %H", ofm_write_data);
                $display("        Golden   : %H", golden_ofm_mem[ofm_write_addr]);
                error_count = error_count + 1;
            end else begin
                $display("[PASS]  Match at addr %0d: %H", ofm_write_addr, ofm_write_data);
            end
        end
        
        if (done) begin
            if (error_count == 0)
                $display("[RESULT] TEST PASSED! No mismatch found.");
            else
                $display("[RESULT] TEST FAILED! %0d mismatches.", error_count);
        end
    end

endmodule
